version: '3.8'

services:
  lavalink:
    container_name: flynn_lavalink
    image: dougley/lavalink
    restart: unless-stopped
    volumes:
      - ./lavalink.yml:/opt/Lavalink/application.yml
    ports:
      - 2333:2333